// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmwojbenogfywrwanhpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtd29qYmVub2dmeXdyd2FuaHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODQ4NDcsImV4cCI6MjA2MDU2MDg0N30.imQy9hiT33ri0UbzSrYP31M2_kTis4p0S-FurPZNrX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);